before_build:
  - nuget restore %solution_name%
  
environment:
  matrix:
  - solution_name: sem4\hw1.5\hw1.5.sln
  
build_script:
  - msbuild %solution_name%

test_script:
  - dotnet test %solution_name%
