before_build:
  - nuget restore %solution_name%
  
environment:
  matrix:
  - solution_name: sem4\hw1.2\hw1.2.sln
  - solution_name: sem4\hw1.3\hw1.3.sln
  - solution_name: sem4\hw1.1\hw1.1.sln
  - solution_name: sem4\hw1.5\hw1.5.sln
  - solution_name: sem4\hw1.4\hw1.4.sln
  - solution_name: sem4\hw2.3\hw2.3.sln
  - solution_name: sem4\hw2.4\hw2.4.sln
  
build_script:
  - msbuild %solution_name%

test_script:
  - dotnet test %solution_name%
